// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvsEBbwZLV5iDYEhYm1R0nqbtbTV57yQQ',
    appId: '1:835844287617:web:f7518f2a1e8e16ccfab180',
    messagingSenderId: '835844287617',
    projectId: 'fireflutter-2a048',
    authDomain: 'fireflutter-2a048.firebaseapp.com',
    storageBucket: 'fireflutter-2a048.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0XJypPy-DjpQhbhPB-6guup4kQS6Pv1s',
    appId: '1:835844287617:android:6faa330a540c3739fab180',
    messagingSenderId: '835844287617',
    projectId: 'fireflutter-2a048',
    storageBucket: 'fireflutter-2a048.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMADUHJ7Jxl-2WTXIE1OPlpdNRNxnReh0',
    appId: '1:835844287617:ios:f5b5e65d7fc91ddafab180',
    messagingSenderId: '835844287617',
    projectId: 'fireflutter-2a048',
    storageBucket: 'fireflutter-2a048.appspot.com',
    iosClientId: '835844287617-p2ah9jhpfusmhobm5ajil7hgis2lmr0g.apps.googleusercontent.com',
    iosBundleId: 'com.murad.fire.flutterFire',
  );
}
